apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cccs.fullname" . }}-read-configmaps
  labels:
    {{- include "cccs.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: User
  name: {{ include "cccs.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "cccs.fullname" . }}-read-configmaps
  apiGroup: rbac.authorization.k8s.io