apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cccs.fullname" . }}-read-configmaps
  labels:
    {{- include "cccs.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "get", "create", "list"]